/** @jsxImportSource @emotion/react */

import { GetStaticProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { FC } from 'react'

import { getAboutPage, getInfo, TAboutPageData, TInfoData } from '../lib/api'
import Layout from '../components/layout'

const getStaticProps: GetStaticProps<{ about: TAboutPageData; info: TInfoData }> = async ({
  locale,
}) => {
  const about = await getAboutPage({ locale })
  const info = await getInfo({ locale })
  const messages = require(`../locales/${locale}.json`)
  return { props: { about, info, messages } }
}

const About: FC<InferGetServerSidePropsType<typeof getStaticProps>> = ({ about, info }) => {
  return (
    <>
      <Head>
        <title>IRESTONE.SPACE | Khan Bifov</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout info={info}>{about.body}</Layout>
    </>
  )
}

export { getStaticProps }
export default About
