/** @jsxImportSource @emotion/react */

import { GetStaticProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { FC } from 'react'
import { useTranslations } from 'use-intl'
import { capitalize } from 'lodash'

import { getInfo, getPosts, TInfoData, TPostData } from '../lib/api'
import Layout from '../components/layout'
import Category from '../components/category'

const getStaticProps: GetStaticProps<{ posts: TPostData[]; info: TInfoData }> = async ({
  locale,
}) => {
  const posts = await getPosts({ locale, where: { category: 'blog' } })
  const info = await getInfo({ locale })
  const messages = require(`../locales/${locale}.json`)
  return { props: { posts, info, messages } }
}

const Blog: FC<InferGetServerSidePropsType<typeof getStaticProps>> = ({ posts, info }) => {
  const t = useTranslations()
  return (
    <>
      <Head>
        <title>IRESTONE.SPACE | {capitalize(t('blog') as string)}</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Layout info={info}>
        <Category title={t('blog') as string} posts={posts} />
      </Layout>
    </>
  )
}

export { getStaticProps }
export default Blog
