import { GetStaticProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import { FC } from 'react'
import { getPosts, TPostData } from '../lib/api'

const getStaticProps: GetStaticProps<{ posts: TPostData[] }> = async () => {
  const posts = await getPosts()
  return { props: { posts } }
}

const Home: FC<InferGetServerSidePropsType<typeof getStaticProps>> = ({ posts }) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {posts.map(({ slug }) => (
        <div key={slug}>{slug}</div>
      ))}
    </div>
  )
}

export { getStaticProps }
export default Home
