/** @jsxImportSource @emotion/react */

import { GetStaticProps, InferGetServerSidePropsType } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { FC } from 'react'

import Layout from '../components/layout'
import { getPosts, TPostData } from '../lib/api'
import { getPostLink } from '../lib/utils'

const getStaticProps: GetStaticProps<{ posts: TPostData[] }> = async ({ locale }) => {
  const posts = await getPosts({ locale })
  return { props: { posts } }
}

const Home: FC<InferGetServerSidePropsType<typeof getStaticProps>> = ({ posts }) => {
  return (
    <>
      <Head>
        <title>IRESTONE.SPACE</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Layout>
        <h3>FEATURED</h3>
        <div css={{ width: '100%', height: '30rem', background: '#ccc' }}></div>
        <h3>LATEST</h3>
        {posts.map((post) => {
          const { id, poster, title, category, tags, created_at } = post
          return (
            <div key={id} css={{ display: 'flex', '& + &': { marginTop: '1rem' } }}>
              <img
                src={poster.url}
                alt={title}
                css={{ width: '7rem', height: '7rem', objectFit: 'cover' }}
              />
              <div css={{ padding: '0 1rem' }}>
                <Link href={getPostLink(post)}>
                  <a
                    css={{
                      margin: 0,
                      color: 'black',
                      fontSize: '1.3rem',
                      fontWeight: 'bold',
                      cursor: 'pointer',
                    }}
                  >
                    {title}
                  </a>
                </Link>
                <p css={{ margin: 0 }}>{category}</p>
                <small>{tags.map((tag) => `#${tag}`).join(' ')}</small>
                <br />
                <small>{created_at}</small>
              </div>
            </div>
          )
        })}
        <h4>{`<pagination>`}</h4>
      </Layout>
    </>
  )
}

// todo: i18n
// todo: click on tag opens a current page w/ the tag param (e.g. .../works?tag=react)

export { getStaticProps }
export default Home
